### ISSUE TITLE
Don't throw an Exception when Attribute specified in Config does not exist

### ISSUE THREAD

**Issue by jorkzijlstra** [Segence/kamon-jmx-collector#11]
We have a common config for all our applications. In this case the config is for bout the Kafka Producer and Kafka Consumer. The application using this config actually might not be a KafKa producer or consume at all, or is just one of them.

We are now getting exceptions in the log when the jmx attribute is missing while we have specified it in the config. I think it would be better to not start collection and just omit this metric.

The reference.conf we are using: [reference.zip](https://github.com/Segence/kamon-jmx-collector/files/2012637/reference.zip)

```
11:41:47.898 TKD [api-push-test-akka.actor.default-dispatcher-8] ERROR o.a.kafka.common.metrics.JmxReporter - Error getting JMX attribute: 
javax.management.AttributeNotFoundException: Could not find attribute request-latency-max
	at org.apache.kafka.common.metrics.JmxReporter$KafkaMbean.getAttribute(JmxReporter.java:189)
	at org.apache.kafka.common.metrics.JmxReporter$KafkaMbean.getAttributes(JmxReporter.java:197)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
	at com.segence.commons.jmx.collector.JmxCollector.lambda$null$1(JmxCollector.java:20)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at scala.collection.convert.Wrappers$MapWrapper$$anon$1$$anon$5.forEachRemaining(Wrappers.scala:181)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.segence.commons.jmx.collector.JmxCollector.queryAsSet(JmxCollector.java:33)
	at kamon.jmx.collector.MetricCollector$.$anonfun$generateMetrics$1(MetricCollector.scala:198)
	at kamon.jmx.collector.MetricCollector$.collectMetrics(MetricCollector.scala:90)
	at kamon.jmx.collector.MetricCollector$.generateMetrics(MetricCollector.scala:198)
	at kamon.jmx.collector.JmxMetricCollectorActor$$anonfun$kamon$jmx$collector$JmxMetricCollectorActor$$waiting$1.applyOrElse(JmxMetricCollectorActor.scala:26)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at kamon.jmx.collector.JmxMetricCollectorActor.aroundReceive(JmxMetricCollectorActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by robvadai** [comment]
I saw the same issue with an application I built. It uses Kafka Consumer 1.0.1 version.
Looks like the Kafka library does the logging on its own: https://github.com/apache/kafka/blob/adec6d6e47e18882ba012ae4f1fa8793c18bd0e1/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java#L205

Maybe you're using an older version that didn't use warning level but logged as error?
Looks like the solution is to override the log level for the `org.apache.kafka.common.metrics` package.

**Comment by robvadai** [comment]
I added this line in my `log4j2.xml` file (I'm bypassing Kafka's `Slf4j` implementation):

    <Logger name="org.apache.kafka.common.metrics" level="ERROR" />

**Comment by robvadai** [comment]
Closing this issue because error reporting is to do with the underlying library that generates the JMX MBeans and properties therefore there are only 2 solution to prevent these kind of errors:
- either remove the query for non-existent metrics from the `application.conf` file
- or silence them by log configuration, depending on your logging library

**Comment by jorkzijlstra** [comment]
@robvadai 

It seems that in newer version of the JmxExporter they changed it form an exception to an logger.error
https://github.com/apache/kafka/blob/1.1/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java#L205
